.PHONY: run time valgrind

run:
	@make -f ../common/makefile --no-print-directory run
time:
	@make -f ../common/makefile --no-print-directory time
valgrind:
	@make -f ../common/makefile --no-print-directory valgrind
